services:
  bittice-server:
    build: .
    container_name: bittice-container
    ports:
      - "3000:3000"
      - "50051:50051"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 500M
    volumes:
      - ./data:/app/data
    environment:
      - BITTICE_HOST=0.0.0.0
    restart: unless-stopped
    command: ["./bittice", "server", "--type", "grpc", "--port", "50051"]

  bittice-cdc:
    build: .
    container_name: bittice-cdc
    depends_on:
      - bittice-server
    environment:
      - BITTICE_HOST=0.0.0.0
    volumes:
      - ./data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    # Conectamos al MySQL que ya tienes corriendo localmente con el password correcto
    command: ["./bittice", "cdc", "--url", "mysql://root:p_ssW0rd@host.docker.internal:3306/sakila", "--entity", "sakila", "--database", "sakila"]
