services:
  bittice-server:
    build: .
    container_name: bittice-container
    ports:
      - "3000:3000"
    # volumes:
      # Montamos la carpeta local "data" en "/app/data" dentro del contenedor
      # Así los datos persisten aunque borres el contenedor.
      # - ./data:/app/data
    environment:
      - BITTICE_HOST=0.0.0.0
    restart: unless-stopped
