#!/usr/bin/env bash
# Builds a folder you can upload to the server: your local data/, .ovpn profiles, compose + .env
# with OpenVPN and bind mounts. After "docker compose up" on the instance, the engine starts with
# the same entity, CDC, and VPN you configured locally.
#
# From the project root (where the data/ directory exists):
#   export BITTICE_IMAGE=ghcr.io/owner/bittice:v0.1.0
#   ./deploy/scripts/export-server-bundle.sh [output-dir]
#
# Optional zip:  (cd .. && zip -r bittice-deploy.zip my-folder)
#
# Warning: the bundle includes cdc_config.json (MySQL credentials) and VPN material. Handle it as a secret.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
# Project root that contains data/ (defaults to the current working directory when you invoke the script).
# Override: BITTICE_PROJECT_ROOT=/path/to/project ./deploy/scripts/export-server-bundle.sh
WORK_ROOT="${BITTICE_PROJECT_ROOT:-$PWD}"
WORK_ROOT="$(cd "$WORK_ROOT" && pwd)"
cd "$WORK_ROOT"

OUT_ARG="${1:-bittice-server-bundle}"
if [[ "$OUT_ARG" = /* ]]; then
  OUT_ABS="$OUT_ARG"
else
  OUT_ABS="$WORK_ROOT/$OUT_ARG"
fi

BITTICE_IMAGE="${BITTICE_IMAGE:-}"
BITTICE_REST_PORT="${BITTICE_REST_PORT:-3000}"
BITTICE_GRPC_PORT="${BITTICE_GRPC_PORT:-50051}"
BITTICE_HOST="${BITTICE_HOST:-0.0.0.0}"

if [[ ! -d data ]]; then
  echo "No data/ directory in $WORK_ROOT. Run this script from the project root (cd there first) or set BITTICE_PROJECT_ROOT." >&2
  exit 1
fi

if ! command -v python3 &>/dev/null; then
  echo "python3 is required on PATH (for cdc_config.json validation)." >&2
  exit 1
fi

mkdir -p "$OUT_ABS"
OUT_ABS="$(cd "$OUT_ABS" && pwd)"

# Data tree: includes data/<entity>/cdc_config.json, tables, data/vpn/, etc.
# tar preserves attributes
tar -C "$WORK_ROOT" -cf - data | tar -C "$OUT_ABS" -xf -

mkdir -p "$OUT_ABS/vpn"

# Profiles: canonical local data/vpn + optional repo-root mount (dev docker-compose)
if [[ -d data/vpn ]]; then
  shopt -s nullglob
  for f in data/vpn/*.ovpn; do
    cp -f "$f" "$OUT_ABS/vpn/"
  done
  shopt -u nullglob
fi
if [[ -d vpn ]]; then
  shopt -s nullglob
  for f in vpn/*.ovpn; do
    cp -f "$f" "$OUT_ABS/vpn/"
  done
  shopt -u nullglob
fi

# Compose template from this repo; the bundle only needs docker-compose.yaml at its root
cp -f "$REPO_ROOT/deploy/docker-compose.bundled.yaml" "$OUT_ABS/docker-compose.yaml"

# .env
if [[ -z "$BITTICE_IMAGE" ]]; then
  echo "Warning: BITTICE_IMAGE is not set; fill it in the bundle's .env before deploy." >&2
  BITTICE_IMAGE="ghcr.io/OWNER/REPO:TAG"
fi
{
  echo "# Generated by deploy/scripts/export-server-bundle.sh"
  echo "BITTICE_IMAGE=$BITTICE_IMAGE"
  echo "BITTICE_HOST=$BITTICE_HOST"
  echo "BITTICE_REST_PORT=$BITTICE_REST_PORT"
  echo "BITTICE_GRPC_PORT=$BITTICE_GRPC_PORT"
  echo "BITTICE_VPN_DIR=/app/vpn"
  echo "BITTICE_VPN_SPLIT_TUNNEL=true"
} > "$OUT_ABS/.env"

cat > "$OUT_ABS/README-DEPLOY.txt" <<'EOF'
Bittice — bundle exported from your local machine

1. Upload this folder to the server (scp, rsync) or zip it first.
2. On the server: Docker + Docker Compose v2. If the image is in a private registry:
     echo TOKEN | docker login ghcr.io -u GITHUB_USER --password-stdin
3. Edit .env if needed (especially BITTICE_IMAGE).
4. From this directory:
     docker compose --env-file .env up -d
5. Verify: docker ps && docker logs bittice

Contains ./data (CDC, tables, cdc_config.json) and ./vpn (.ovpn profiles). Do not share this bundle publicly; it includes credentials.
EOF

# Ensure each cdc_config vpn_file has a matching .ovpn in the bundle (by file name)
python3 <<PY
import json, os, sys
from pathlib import Path

out = Path(r"""$OUT_ABS""")
vpn_in_pack = (out / "vpn")
data_in_pack = (out / "data")

ok = True
def has_ovpn(basename: str) -> bool:
    if not basename.endswith(".ovpn"):
        return False
    a = vpn_in_pack / basename
    b = data_in_pack / "vpn" / basename
    return a.is_file() or b.is_file()

for cfg in data_in_pack.glob("*/cdc_config.json"):
    try:
        j = json.loads(cfg.read_text())
    except Exception as e:
        print(f"Warning: could not read {cfg}: {e}", file=sys.stderr)
        continue
    v = j.get("vpn_file")
    if not v:
        continue
    name = os.path.basename(v)
    if not has_ovpn(name):
        print(f"Error: {cfg} references VPN '{v}' but {name} was not found in vpn/ or data/vpn/ in the bundle.", file=sys.stderr)
        ok = False

sys.exit(0 if ok else 1)
PY

echo "Done: $OUT_ABS"
echo "Next: upload that folder to the server and run: docker compose --env-file .env up -d"
